spring:
  web:
    resourses:
      static-locations:
        - file:src/main/resources/public/
        - classpath:/public/
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: dim
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005